= Suporte de resposta do rastreador
:allow-uri-read: 




=== Suporte de resposta do rastreador

O Tracker agora fornece respostas de API para que você possa ver a saída da API REST relacionada à tarefa.



=== Suporte de autenticação de link para o AWS Secrets Manager

Agora você tem a opção de usar segredos do AWS Secrets Manager para autenticar links, para que não precise usar credenciais armazenadas no BlueXP Workloads.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Conecte-se a um sistema de arquivos FSx para ONTAP com um link Lambda"^]



=== Implementar as melhores práticas para um sistema de arquivos FSx para ONTAP

O BlueXP Workloads fornece um painel onde você pode revisar o status bem arquitetado das configurações do seu sistema de arquivos.  Você pode aproveitar essa análise para implementar as melhores práticas para seus sistemas de arquivos FSx para ONTAP .  A análise de configuração do sistema de arquivos inclui as seguintes configurações: limite de capacidade do SSD, snapshots locais agendados, FSx agendado para backups ONTAP , hierarquização de dados e replicação remota de dados.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["Aprenda sobre a análise bem arquitetada para configurações de sistemas de arquivos"^]
* link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_well-architected/improve-configurations.html["Implemente as melhores práticas para seus sistemas de arquivos"^]




=== Notificação bem arquitetada para problemas no sistema de arquivos

No console BlueXP , o FSx para sistemas de arquivos ONTAP com problemas bem arquitetados agora exibe uma notificação no Canvas indicando quando os sistemas de arquivos têm problemas a serem corrigidos.



=== Terminologia de permissões atualizada

A interface do usuário e a documentação do Workload Factory agora usam "somente leitura" para se referir às permissões de leitura e "leitura/gravação" para se referir às permissões de automação.
