---
sidebar: sidebar 
permalink: use/task-manage-fsx-systems.html 
keywords: amazon fsx for netapp ontap, fsx, manage fsx for ontap system, delete fsx for ontap system, remove fsx for ontap system, throughput capacity, change throughput, automatic capacity management, capacity management, storage capacity, replication, classification, sync, backup, recovery, bluexp, NetApp Console 
summary: Depois de criar ou descobrir um sistema FSx para ONTAP no NetApp Console, você pode gerenciar o sistema de arquivos e usar os serviços de dados do NetApp que fornecem recursos como backup e recuperação. 
---
= Gerenciar um sistema de arquivos FSx para ONTAP no NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Depois de criar ou descobrir um sistema FSx para ONTAP no NetApp Console, você pode gerenciar o sistema de arquivos criando volumes, gerenciando VMs de armazenamento, protegendo dados e administrando o sistema de arquivos.  O Console também permite que você use serviços de dados que fornecem recursos como backup e recuperação, classificação de dados, sincronização de dados e muito mais.



== Gerenciar um sistema de arquivos usando o NetApp Workloads

Ao abrir um sistema FSx for ONTAP na página NetApp Console Systems, você é levado para NetApp Workloads.  Workloads é um serviço inteligente de otimização e automação que usa as melhores práticas do setor para projetar, configurar e operar cargas de trabalho importantes usando o Amazon FSx for NetApp ONTAP.

https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["Aprenda a gerenciar um sistema de arquivos usando o NetApp Workloads"^]



== Gerenciar um sistema de arquivos usando o ONTAP System Manager

Você pode gerenciar um sistema de arquivos FSx para ONTAP diretamente do Console usando a interface do ONTAP System Manager.  Um agente de console é necessário para usar o System Manager.



== Gerenciar um sistema de arquivos usando o Amazon CloudFormation

Você pode provisionar e gerenciar o FSx para recursos do sistema de arquivos ONTAP (volumes, compartilhamentos CIFS, políticas de exportação e muito mais) usando o Amazon CloudFormation.

link:https://github.com/NetApp/NetApp-CloudFormation-FSx-ONTAP-provider["Repositório GitHub do provedor NetApp CloudFormation FSx para ONTAP"^]



== Use serviços de dados NetApp com um sistema de arquivos

Use os serviços de dados da NetApp com seus sistemas de arquivos FSx for ONTAP para fazer backup e recuperar seus dados, transferir e sincronizar dados, digitalizar e classificar seus dados, replicar dados e acelerar o acesso ou descarregar o tráfego.



=== Faça backup e recupere seus dados

O NetApp Backup and Recovery oferece proteção de dados eficiente, segura e econômica para dados, bancos de dados e máquinas virtuais do NetApp ONTAP , tanto no local quanto na nuvem.

link:https://docs.netapp.com/us-en/data-services-backup-recovery/index.html["Comece a usar o NetApp Backup and Recovery"^]



=== Transferir e sincronizar dados

O NetApp Copy and Sync é um serviço de replicação e sincronização em nuvem para transferência de dados NAS entre armazenamentos de objetos locais e na nuvem.

link:https://docs.netapp.com/us-en/data-services-copy-sync/task-quick-start.html["Comece a usar o NetApp Copy and Sync"^]



=== Digitalize e classifique seus dados

A NetApp Data Classification permite que você escaneie e classifique dados na multinuvem híbrida da sua organização.

link:https://docs.netapp.com/us-en/data-services-data-classification/index.html["Comece a usar a NetApp Data Classification"^]



=== Replicar dados

Replique dados para dar suporte a backup e recuperação de desastres. A replicação de dados entre um sistema de arquivos FSx for ONTAP e o Cloud Volumes ONTAP pode ser realizada usando o NetApp Replication. A replicação permite que você replique dados entre sistemas de armazenamento ONTAP para dar suporte a backup e recuperação de desastres na nuvem ou entre nuvens.

link:https://docs.netapp.com/us-en/data-services-replication/task-replicating-data.html["Comece a usar a NetApp Replication"^]

A replicação de dados entre dois sistemas de arquivos FSx for ONTAP e entre um sistema ONTAP local e um sistema de arquivos FSx for ONTAP é possível a partir da página de sistemas do NetApp Console .

.Antes de começar
Considere o seguinte antes de começar.

* Para replicar dados entre dois sistemas de arquivos FSx for ONTAP ou entre um sistema ONTAP local e um sistema de arquivos FSx for ONTAP , você deve selecionar um agente de console com conectividade ao sistema de arquivos ou inserir o sistema de arquivos para associar um link.
* A replicação não é suportada para volumes em um estado diferente de disponível, criado ou mal configurado e quando a versão do ONTAP não é compatível.


.Passos
. Na página Sistemas do NetApp Console , arraste o sistema de arquivos FSx for ONTAP de origem ou o sistema ONTAP local para cima do sistema de arquivos FSx for ONTAP de destino e selecione *Replicação*.
. Na página Criar replicação, selecione os volumes de origem a serem replicados e depois *Avançar*.
. Em Destino de replicação, forneça o seguinte:
+
.. *Nome do alvo*: O nome do alvo foi selecionado anteriormente durante a operação de arrastar e soltar na tela.
.. *Nome da VM de armazenamento*: Selecione a VM de armazenamento no menu suspenso.  A VM de armazenamento selecionada é o destino para todos os volumes selecionados neste relacionamento de replicação.
.. *Nome do volume*: O nome do volume de destino é gerado automaticamente com o seguinte formato `{OriginalVolumeName}_copy` .  Você pode usar o nome do volume gerado automaticamente ou inserir outro nome de volume.
.. *Caso de uso*: Selecione um dos seguintes casos de uso para a replicação.  Dependendo do caso de uso selecionado, o Workload Factory preenche o formulário com valores recomendados de acordo com as melhores práticas.  Você pode aceitar os valores recomendados ou fazer alterações à medida que preenche o formulário.
+
*** Migração: transfere seus dados para o sistema de arquivos FSx for ONTAP de destino
*** Recuperação de desastres a quente: garante alta disponibilidade e recuperação rápida de desastres para cargas de trabalho críticas
*** Recuperação de desastres a frio ou arquivados:
+
**** Recuperação de desastres a frio: usa objetivos de tempo de recuperação (RTO) e objetos de ponto de recuperação (RPO) mais longos para reduzir custos
**** Arquivo: replica dados para armazenamento de longo prazo e conformidade


*** Outro
+
Além disso, a seleção do caso de uso determina a política de replicação, ou política SnapMirror (ONTAP).  Os termos usados ​​para descrever as políticas de replicação vêm delink:https://docs.netapp.com/us-en/ontap/data-protection/default-protection-policies-concept.html["Documentação do ONTAP 9"^] .

+
**** Para migração e outros, a política de replicação é chamada _MirrorAllSnapshots_.  _MirrorAllSnapshots_ é uma política assíncrona para espelhar todos os snapshots e o último sistema de arquivos ativo.
**** Para recuperação de desastres a quente, a frio ou de arquivo, a política de replicação é chamada _MirrorAndVault_.  _MirrorAndVault_ é uma política assíncrona e de cofre para espelhar o sistema de arquivos ativo mais recente e instantâneos diários e semanais.
+
Para todos os casos de uso, se você habilitar snapshots para retenção de longo prazo, a política de replicação padrão será _MirrorAndVault_.





.. *Política de níveis*: Selecione a política de níveis para os dados armazenados no volume de destino.  A política de camadas assume como padrão a política de camadas recomendada para o caso de uso selecionado.
+
_Balanceado (Automático)_ é a política de camadas padrão ao criar um volume usando o console do Workload Factory.  Para obter mais informações sobre políticas de níveis de volume, consultelink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Capacidade de armazenamento de volume"^] na documentação do AWS FSx para NetApp ONTAP .  Observe que o Workload Factory usa nomes baseados em casos de uso no console do Workload Factory para políticas de camadas e inclui nomes de políticas de camadas do FSx para ONTAP entre parênteses.

+
Se você selecionou o caso de uso de migração, o Workload Factory seleciona automaticamente copiar a política de camadas do volume de origem para o volume de destino.  Você pode desmarcar a opção de copiar a política de camadas e selecionar uma política de camadas que se aplique ao volume selecionado para replicação.

.. *Taxa máxima de transferência*: Selecione *Limitado* e insira o limite máximo de transferência em MB/s.  Como alternativa, selecione *Ilimitado*.
+
Sem um limite, o desempenho da rede e dos aplicativos pode diminuir.  Como alternativa, recomendamos uma taxa de transferência ilimitada para sistemas de arquivos FSx for ONTAP para cargas de trabalho críticas, por exemplo, aquelas usadas principalmente para recuperação de desastres.



. Em Configurações de replicação, forneça o seguinte:
+
.. *Intervalo de replicação*: selecione a frequência com que os instantâneos são transferidos do volume de origem para o volume de destino.
.. *Retenção de longo prazo*: Opcionalmente, habilite snapshots para retenção de longo prazo.  A retenção de longo prazo permite que os serviços empresariais continuem operando mesmo em caso de falha completa do site, permitindo que os aplicativos passem por failover de forma transparente usando uma cópia secundária.
+
Replicações sem retenção de longo prazo usam a política _MirrorAllSnapshots_.  Habilitar a retenção de longo prazo atribui a política _MirrorAndVault_ à replicação.

+
Se você habilitar a retenção de longo prazo, selecione uma política existente ou crie uma nova política para definir os snapshots a serem replicados e o número a ser retido.

+

NOTE: A correspondência de rótulos de origem e destino é necessária para retenção de longo prazo.  Se desejar, o Workload Factory pode criar rótulos ausentes para você.

+
*** *Escolha uma política existente*: selecione uma política existente no menu suspenso.
*** *Criar uma nova política*: insira um *nome de política*.


.. *Snapshots imutáveis*: Opcional.  Selecione *Ativar snapshots imutáveis* para evitar que snapshots tirados nesta política sejam excluídos durante o período de retenção.
+
*** Defina o *Período de retenção* em número de horas, dias, meses ou anos.
*** *Políticas de snapshot*: Na tabela, selecione a frequência da política de snapshot e o número de cópias a serem retidas.  Você pode selecionar mais de uma política de instantâneo.






. Selecione *Criar*.




=== Acelere o acesso ou descarregue o tráfego

O NetApp Volume Caching fornece um volume persistente e gravável em um local remoto.  Você pode usar o cache de volume para acelerar o acesso aos dados ou para descarregar o tráfego de volumes muito acessados.

link:https://docs.netapp.com/us-en/console-volume-caching/get-started/cache-intro.html["Comece a usar o NetApp Volume Caching"^]
