---
sidebar: sidebar 
permalink: use/task-remove-filesystem.html 
keywords: amazon fsx for netapp ontap, fsx for ontap, fsx, remove fsx for ontap file system, remove file system, file system, disassociate file system, bluexp, NetApp Console 
summary: Remova um sistema de arquivos FSx para ONTAP de um projeto no NetApp Console. 
---
= Remover um sistema de arquivos FSx para ONTAP de um projeto
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Remova um sistema de arquivos FSx para ONTAP de um projeto no NetApp Console.  Esta operação dissocia o sistema de arquivos de um projeto para que você possa associá-lo a outro projeto dentro da mesma conta.

.Sobre esta tarefa
Remover um sistema de arquivos FSx para ONTAP de um projeto o remove do NetApp Console.  Ele não exclui o sistema de arquivos FSx para ONTAP .  Mais tarde, você pode redescobrir o sistema de arquivos FSx para ONTAP no mesmo projeto ou em um projeto diferente dentro da mesma conta.

.Passos
. No menu do NetApp Console , selecione *Armazenamento* e depois *Gerenciamento*.
. Selecione o sistema de arquivos que você deseja remover.
. Selecione *Entrar no sistema*.
. No FSx para ONTAP no Armazenamento, selecione o menu de três pontos e, em seguida, selecione *Remover do projeto*.
. Selecione *Remover* para confirmar a remoção do sistema de arquivos do projeto.

