---
sidebar: sidebar 
permalink: use/task-manage-fsx-systems.html 
keywords: amazon fsx for netapp ontap, fsx, manage fsx for ontap system, delete fsx for ontap system, remove fsx for ontap system, throughput capacity, change throughput, automatic capacity management, capacity management, storage capacity, replication, classification, sync, backup, recovery, bluexp, NetApp Console 
summary: Depois de criar ou descobrir um sistema FSx para ONTAP no NetApp Console, você pode gerenciar o sistema de arquivos e usar os serviços de dados do NetApp que fornecem recursos como backup e recuperação. 
---
= Gerenciar um sistema de arquivos FSx para ONTAP no NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Depois de criar ou descobrir um sistema FSx para ONTAP no NetApp Console, você pode gerenciar o sistema de arquivos criando volumes, gerenciando VMs de armazenamento, protegendo dados e administrando o sistema de arquivos.  O Console também permite que você use serviços de dados que fornecem recursos como backup e recuperação, classificação de dados, sincronização de dados e muito mais.



== Gerenciar um sistema de arquivos usando o NetApp Workloads

Ao abrir um sistema FSx for ONTAP na página Systems do NetApp Console, você é direcionado para o NetApp Workloads. Workloads é um serviço inteligente de otimização e automação que utiliza as melhores práticas do setor para planejar, provisionar e operar cargas de trabalho essenciais usando Amazon FSx for NetApp ONTAP.

https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["Aprenda a gerenciar um sistema de arquivos usando o NetApp Workloads"^]



== Gerenciar um sistema de arquivos usando o ONTAP System Manager

Você pode gerenciar um sistema de arquivos FSx para ONTAP diretamente do Console usando a interface do ONTAP System Manager. É necessário um agente de console ou um link do AWS Lambda para usar o System Manager.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["Aprenda a usar links"^]



== Gerenciar um sistema de arquivos usando o Amazon CloudFormation

Você pode provisionar e gerenciar o FSx para recursos do sistema de arquivos ONTAP (volumes, compartilhamentos CIFS, políticas de exportação e muito mais) usando o Amazon CloudFormation.

link:https://github.com/NetApp/NetApp-CloudFormation-FSx-ONTAP-provider["Repositório GitHub do provedor NetApp CloudFormation FSx para ONTAP"^]



== Use serviços de dados NetApp com um sistema de arquivos

Use os serviços de dados da NetApp com seus sistemas de arquivos FSx for ONTAP para fazer backup e recuperar seus dados, transferir e sincronizar dados, digitalizar e classificar seus dados, replicar dados e acelerar o acesso ou descarregar o tráfego.



=== Faça backup e recupere seus dados

O NetApp Backup and Recovery oferece proteção de dados eficiente, segura e econômica para dados, bancos de dados e máquinas virtuais do NetApp ONTAP , tanto no local quanto na nuvem.

link:https://docs.netapp.com/us-en/data-services-backup-recovery/index.html["Comece a usar o NetApp Backup and Recovery"^]



=== Transferir e sincronizar dados

O NetApp Copy and Sync é um serviço de replicação e sincronização em nuvem para transferência de dados NAS entre armazenamentos de objetos locais e na nuvem.

link:https://docs.netapp.com/us-en/data-services-copy-sync/task-quick-start.html["Comece a usar o NetApp Copy and Sync"^]



=== Digitalize e classifique seus dados

A NetApp Data Classification permite que você escaneie e classifique dados na multinuvem híbrida da sua organização.

link:https://docs.netapp.com/us-en/data-services-data-classification/index.html["Comece a usar a NetApp Data Classification"^]



=== Acelere o acesso ou descarregue o tráfego

O NetApp Volume Caching fornece um volume persistente e gravável em um local remoto.  Você pode usar o cache de volume para acelerar o acesso aos dados ou para descarregar o tráfego de volumes muito acessados.

link:https://docs.netapp.com/us-en/console-volume-caching/get-started/cache-intro.html["Comece a usar o NetApp Volume Caching"^]
